/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  wikiSidebar: [{ type: 'autogenerated', dirName: 'wiki' }],
  essaySidebar: [{ type: 'autogenerated', dirName: 'essay' }],
  snippetSidebar: [{ type: 'autogenerated', dirName: 'snippet' }],
  retrospectiveSidebar: [{ type: 'autogenerated', dirName: 'retrospective' }],
};

export default sidebars;
